version: "3"

services:
  jenkins-url-requester:
    image: "jenkins-url-requester"
    ports:
      - "48080:8080"
    environment:
      - BUILD_SERVER_DOMAIN=https://build.com # 젠킨스 서버
      - BUILD_USERNAME=yhchoi # 젠킨스 계정
      - BUILD_USER_TOKEN= # 젠킨스 > 로그인 > 사용자 > 설정 > API Token